<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_04292020</name>
   <tag></tag>
   <elementGuidId>7cd542b2-d4db-4e01-a836-fcf8018a6022</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root-610 MuiTypography-h3-617</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>task-attribute</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>04/29/2020</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;jss86&quot;]/div[@class=&quot;jss156 jss157&quot;]/div[@class=&quot;jss158&quot;]/main[@class=&quot;jss323 jss324&quot;]/div[@class=&quot;MuiContainer-root-325 MuiContainer-maxWidthLg-331&quot;]/div[@class=&quot;MuiGrid-root-333 MuiGrid-item-335&quot;]/div[@class=&quot;jss516&quot;]/div[@class=&quot;MuiPaper-root-554 MuiExpansionPanel-root-550 MuiExpansionPanel-rounded-551 MuiPaper-elevation1-558 MuiPaper-rounded-555&quot;]/div[@class=&quot;MuiButtonBase-root-463 MuiExpansionPanelSummary-root-582&quot;]/div[@class=&quot;MuiExpansionPanelSummary-content-586&quot;]/div[@class=&quot;MuiGrid-root-333 MuiGrid-container-334 MuiGrid-align-items-xs-center-342&quot;]/div[@class=&quot;MuiGrid-root-333 MuiGrid-item-335 MuiGrid-grid-xs-true-367&quot;]/div[@class=&quot;MuiGrid-root-333 MuiGrid-container-334 MuiGrid-spacing-xs-3-358 MuiGrid-align-items-xs-center-342&quot;]/div[@class=&quot;MuiGrid-root-333 MuiGrid-item-335&quot;]/h3[@class=&quot;MuiTypography-root-610 MuiTypography-h3-617&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div/main/div/div[2]/div/div[3]/div/div/div/div[2]/div/div/h3</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::h3[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closed'])[2]/following::h3[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draw Date'])[2]/preceding::h3[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit Date'])[2]/preceding::h3[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='04/29/2020']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/h3</value>
   </webElementXpaths>
</WebElementEntity>
