<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Completed_Search</name>
   <tag></tag>
   <elementGuidId>1eec9c90-6876-457b-a6c0-01c5e715c232</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-503 MuiOutlinedInput-input-487 MuiInputBase-inputTypeSearch-508</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;jss86&quot;]/div[@class=&quot;jss156 jss157&quot;]/div[@class=&quot;jss158&quot;]/main[@class=&quot;jss323 jss324&quot;]/div[@class=&quot;MuiContainer-root-325 MuiContainer-maxWidthLg-331&quot;]/div[@class=&quot;MuiGrid-root-333 MuiGrid-item-335&quot;]/div[@class=&quot;MuiBox-root-436 jss437&quot;]/div[@class=&quot;jss471&quot;]/div[@class=&quot;MuiFormControl-root-473 MuiTextField-root-472 MuiFormControl-fullWidth-476&quot;]/div[@class=&quot;MuiInputBase-root-492 MuiOutlinedInput-root-477 MuiInputBase-fullWidth-502 Mui-focused Mui-focused MuiInputBase-formControl-493&quot;]/input[@class=&quot;MuiInputBase-input-503 MuiOutlinedInput-input-487 MuiInputBase-inputTypeSearch-508&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Search']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div/main/div/div/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
