<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fundLabel</name>
   <tag></tag>
   <elementGuidId>46d90df5-4525-4d61-8d40-16f3d8dc922b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/div/div[1]/div/main/div[2]/div[2]/div/div[2]/table/thead/tr/th[5]/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
