<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invoiceListOptions</name>
   <tag></tag>
   <elementGuidId>77fe8f57-596b-4530-a5d5-b7605403e23f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@class,'MuiAutocomplete-option-')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-root-2673 MuiOutlinedInput-root-2658 MuiAutocomplete-inputRoot-2616 MuiInputBase-fullWidth-2683 MuiInputBase-formControl-2674 MuiInputBase-adornedEnd-2678 MuiOutlinedInput-adornedEnd-2663</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invoice #</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDrawer-root-1454 MuiDrawer-modal-1465&quot;]/div[@class=&quot;MuiPaper-root-80 MuiDrawer-paper-1456 MuiDrawer-paperAnchorBottom-1460 MuiPaper-elevation16-99&quot;]/div[@class=&quot;jss2596 jss2597&quot;]/div[@class=&quot;jss2598&quot;]/div[@class=&quot;jss2601&quot;]/div[1]/div[@class=&quot;MuiContainer-root-292 MuiContainer-maxWidthLg-298&quot;]/div[@class=&quot;jss2604 jss2605&quot;]/div[@class=&quot;MuiGrid-root-149 MuiGrid-container-150 MuiGrid-spacing-xs-4-175&quot;]/div[@class=&quot;MuiGrid-root-149 MuiGrid-item-151 MuiGrid-grid-xs-3-186&quot;]/div[@class=&quot;MuiAutocomplete-root-2610 MuiAutocomplete-hasClearIcon-2615&quot;]/div[@class=&quot;MuiFormControl-root-2634 MuiTextField-root-2633 MuiFormControl-fullWidth-2637&quot;]/div[@class=&quot;MuiInputBase-root-2673 MuiOutlinedInput-root-2658 MuiAutocomplete-inputRoot-2616 MuiInputBase-fullWidth-2683 MuiInputBase-formControl-2674 MuiInputBase-adornedEnd-2678 MuiOutlinedInput-adornedEnd-2663&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*[contains(@class,'MuiAutocomplete-option-')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice #'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add invoice manually'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
