<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InvExpandButton</name>
   <tag></tag>
   <elementGuidId>33d1d4ea-3a55-4afd-9e2c-9d3e2d93c066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'MuiBox-root')]/parent::div/parent::div[1]/div[1]//a[@data-id=&quot;button-link&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
