<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ReceiptNotes</description>
   <name>ReceiptNotes</name>
   <tag></tag>
   <elementGuidId>7fbc2454-3845-4ca0-a1ab-fd327d0d9d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
