<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete-distributionline</name>
   <tag></tag>
   <elementGuidId>579cdf90-b942-4c8d-b07d-ff5dab29b2dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Delete' or . = 'Delete')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;long-menu&quot;]/div[3]/ul/li[2]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-5630 MuiListItem-root-5890 MuiMenuItem-root-5886 MuiMenuItem-gutters-5887 MuiListItem-gutters-5897 MuiListItem-button-5898</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;long-menu&quot;]/div[@class=&quot;MuiPaper-root-5721 MuiMenu-paper-5644 MuiPopover-paper-5647 MuiPaper-elevation8-5732 MuiPaper-rounded-5722&quot;]/ul[@class=&quot;MuiList-root-5882 MuiMenu-list-5645 MuiList-padding-5883&quot;]/li[@class=&quot;MuiButtonBase-root-5630 MuiListItem-root-5890 MuiMenuItem-root-5886 MuiMenuItem-gutters-5887 MuiListItem-gutters-5897 MuiListItem-button-5898&quot;]</value>
   </webElementProperties>
</WebElementEntity>
