<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quarterlyTransactionReportHeader</name>
   <tag></tag>
   <elementGuidId>252b9a44-ee9b-4910-a138-71ad8628ff4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/main/div/div/div/div/main/div[1]/div[2]/div/h5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
