<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>IncorrectPayDate</description>
   <name>IncorrectPayDate</name>
   <tag></tag>
   <elementGuidId>05ad7420-a29f-42ff-bd8c-9d50a7149f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@data-id='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
