<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>IncorrectDrawDate</description>
   <name>IncorrectDrawDate</name>
   <tag></tag>
   <elementGuidId>0dae8d10-9396-4cc8-a5f6-68a3d5c9b896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@data-id='checkbox'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
