<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lineNumberLabel</name>
   <tag></tag>
   <elementGuidId>611fc68b-f684-4e98-bbc3-b7cdebeb5e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/main/div/div/div/div/main/div[2]/div[2]/div/div[2]/table/thead/tr/th[1]/h6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
