<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ReceiptSearchBar</description>
   <name>ReceiptSearchBar</name>
   <tag></tag>
   <elementGuidId>3e1c1c55-2d92-488b-b6b2-fe8276e0efb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
