<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resumeBatch</name>
   <tag></tag>
   <elementGuidId>3ae85ed8-bf67-46cd-b56a-e1f8d67b7c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/div/div/div/main/div/div[3]/div/div[2]/div[1]/div/div[9]/div/div/a/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
